name = "matrix_gleam"
version = "0.2.0"

description = "Matrix mathematics for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "seancribbs", repo = "matrix" }

internal_modules = [
  "matrix/internal/*",
]


[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
vec = ">= 4.1.0 and < 5.0.0"
gleam_community_maths = ">= 2.0.1 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
